### ISSUE TITLE
Make the readme.md more readable 

### ISSUE THREAD

**Issue by SaharshDaNerd** [ietebitmesra/Hacktoberfest-23#12]
The current readme file is very clunky and can be very overwhelming for a new developer, it doesn't have the right markdown used either. Just a tiny few changes will make it feel better.

**Comment by achuehuehue** [comment]
Please assign this issue to me.

**Comment by achuehuehue** [comment]
@HarshRaj4523 
@Aryashre14 
please assign this issue to me.
