### ISSUE TITLE
Add "About" and "Contact Us" route

### ISSUE THREAD

**Issue by HarshRaj4523** [ietebitmesra/Hacktoberfest-23#2]

**Comment by SanjanaReddy7707** [comment]
@HarshRaj4523 
Hi, I'm interested in working on this issue. Could you please assign it to me? 
Thanks!

**Comment by Asheklm6** [comment]
@HarshRaj4523  Please can you assign this to me under the label Hacktoberfest, in addition is there any specific information to be included for the "About" and "Contact Us" route?

**Comment by Asheklm6** [comment]
Added "About" and "Contact Us" route #2
